#! /bin/sh
DIR=`dirname $0`

if [ -x $DIR/inet -o -x $DIR/inet.exe ]; then
  echo $DIR/inet -n $DIR/../examples:$DIR $*
  $DIR/inet -n $DIR/../examples:$DIR $*
else
  echo opp_run -l $DIR/inet -n $DIR/../examples:$DIR $*
  opp_run -l $DIR/inet -n $DIR/../examples:$DIR $*
fi
