#!/bin/bash

../../../src/inet -r 0 -u Cmdenv -c Default_Netperfmeter -n ../..:../../../simulations:../../../src  omnetpp.ini > dat.log 2> err.log 
cat err.log | grep "[DSS][STATUS]" > dss_status.log &

echo "Grep DSS RCV Status > dss_rcv_status.log"; 
cat err.log | grep "\[FLOW\]\[RCV\]\[DSS\]\[STATUS\]" > dss_rcv_status.log &
echo "Grep DSS SND Status > dss_snd_status.log";
cat err.log | grep "\[FLOW\]\[SND\]\[DSS\]\[STATUS\]" > dss_snd_status.log &
